"""
About

StockVision Forecast V2
"""

import sys
from pathlib import Path

# ==========================================================
# Add Project Root
# ==========================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

# ==========================================================
# Imports
# ==========================================================

import streamlit as st
from src.startup import initialize_app
from streamlit_app.theme import render_theme_controls
# ==========================================================
# Load CSS
# ==========================================================

css_file = (

    PROJECT_ROOT

    / "streamlit_app"

    / "assets"

    / "styles.css"

)

if css_file.exists():

    with open(css_file) as f:

        st.markdown(

            f"<style>{f.read()}</style>",

            unsafe_allow_html=True

        )

# ==========================================================
# Page Configuration
# ==========================================================

st.set_page_config(

    page_title="About",

    page_icon="ℹ️",

    layout="wide"

)
# ==========================================================
# Application Startup
# ==========================================================

initialize_app()

with st.sidebar:

    render_theme_controls()
# ==========================================================
# Hero Section
# ==========================================================

st.title("ℹ️ About This Project")

st.markdown(
"""
### StockVision Forecast V2

StockVision Forecast V2 is a **production-style Machine Learning
application** developed to predict the **next trading day's
closing price** using historical stock market data and
live Yahoo Finance data.

This page explains the motivation behind the project,
its architecture, Machine Learning methodology,
design decisions and future roadmap.
"""
)

st.success(
"""
📘 **Project Documentation**

✔ Problem Statement
&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
✔ System Architecture
&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
✔ Machine Learning Methodology
&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
✔ Future Roadmap
"""
)

st.divider()
# ==========================================================
# Problem Statement
# ==========================================================

st.header("🎯 Problem Statement")

st.write(
"""
Financial markets generate enormous amounts of data every
trading day, making it difficult for investors and analysts
to estimate future stock prices manually.

The objective of **StockVision Forecast V2** is to develop
an end-to-end Machine Learning application capable of
predicting the **next trading day's closing price** using
historical stock prices and technical indicators.

The project focuses on building a complete prediction
pipeline rather than simply training a Machine Learning model.
It includes live data acquisition, feature engineering,
prediction generation, automatic history tracking and
prediction verification.
"""
)

st.divider()
# ==========================================================
# System Architecture
# ==========================================================

st.header("🏗️ System Architecture")

st.write(
"""
StockVision Forecast V2 follows a modular architecture
where each component is responsible for a specific task
within the prediction pipeline.
"""
)

st.code(
"""
                USER
                  │
                  ▼
        Streamlit Web Interface
                  │
                  ▼
      Company Selection (Ticker)
                  │
                  ▼
      Yahoo Finance Live Data
                  │
                  ▼
       Feature Engineering
       (Technical Indicators)
                  │
                  ▼
        Linear Regression Model
                  │
                  ▼
    Next Trading Day Prediction
                  │
                  ▼
        Store Prediction
            (PostgreSQL)
                  │
                  ▼
        Automatic Prediction
            Verification
                  │
                  ▼
        Update Prediction Status
            (PostgreSQL)
""",
language="text"
)

st.info(
"""
Every prediction generated by the application is automatically
stored in the PostgreSQL database along with its prediction
metadata.

When the target trading day has passed, the application
downloads the actual closing price from Yahoo Finance,
verifies the prediction, and updates the same PostgreSQL
record with the actual closing price, prediction error,
and verification status automatically.
"""
)

st.divider()

# ==========================================================
# Machine Learning Methodology
# ==========================================================

st.header("🧠 Machine Learning Methodology")

st.markdown(
"""
The prediction model follows a supervised Machine Learning
workflow consisting of the following stages:

### 📥 Data Collection

- Historical stock prices downloaded from Yahoo Finance
- OHLCV market data
- Daily updated datasets

---

### ⚙️ Feature Engineering

Technical indicators are generated from the raw data,
including:

- Moving Averages (MA)
- Exponential Moving Average (EMA)
- Relative Strength Index (RSI)
- MACD
- Bollinger Bands
- Daily Returns
- Rolling Volatility
- Lag Features

---

### 🤖 Model Training

The engineered dataset is used to train a
**Linear Regression** model.

Multiple models were evaluated during experimentation,
including:

- Linear Regression
- HistGradientBoosting
- XGBoost
- LightGBM

Linear Regression delivered the best overall performance
for this dataset.

---

### 🎯 Prediction

The trained model predicts the **next trading day's
closing price**, after which the prediction is stored
and later verified using the actual market close.
"""
)

st.divider()

# ==========================================================
# Why Linear Regression?
# ==========================================================

st.header("🤖 Why Linear Regression?")

st.write(
"""
Several Machine Learning algorithms were evaluated during
the development of StockVision Forecast V2.

After comparing multiple regression models, **Linear Regression**
was selected because it consistently produced the best balance
between prediction accuracy, stability, simplicity and
computational efficiency for this dataset.
"""
)

comparison1, comparison2 = st.columns(2)

with comparison1:

    st.success(
"""
### ✅ Advantages

• Highest prediction accuracy

• Excellent R² Score

• Low prediction error

• Fast training

• Fast prediction

• Easy deployment

• Highly interpretable
"""
    )

with comparison2:

    st.info(
"""
### 📊 Models Evaluated

• Linear Regression

• HistGradientBoosting

• XGBoost

• LightGBM

After evaluation,
**Linear Regression**
achieved the best overall performance.
"""
    )

st.divider()
# ==========================================================
# Model Evaluation
# ==========================================================

st.header("📊 Model Evaluation")

m1, m2, m3, m4 = st.columns(4)

with m1:

    st.metric(
        "Prediction Accuracy",
        "98.62%"
    )

with m2:

    st.metric(
        "R² Score",
        "0.9995"
    )

with m3:

    st.metric(
        "MAE",
        "$2.34"
    )

with m4:

    st.metric(
        "RMSE",
        "$5.97"
    )

st.divider()
# ==========================================================
# Learn About Model Metrics
# ==========================================================

with st.expander("📚 Learn About Model Evaluation Metrics"):

    st.markdown(
"""
### 🎯 Prediction Accuracy

Regression models do not naturally provide an accuracy score.

To make performance easier to understand, the application derives
Prediction Accuracy from **MAPE**:

**Accuracy = (1 − MAPE) × 100**

For this project:

**Prediction Accuracy = 98.62%**

---

### 📈 R² Score

Measures how well the model explains changes in stock prices.

**Result:** 0.9995

This indicates that the model explains almost all of the variance
present in the test dataset.

---

### 💵 MAE

Average absolute prediction error.

**Result:** $2.34

On average, the prediction differs from the actual closing
price by approximately **$2.34**.

---

### 📉 RMSE

Measures larger prediction errors more heavily.

**Result:** $5.97

A relatively low RMSE indicates that large prediction errors
are uncommon.

---

### 📊 MAPE

Mean Absolute Percentage Error.

**Result:** 1.38%

This value is also used to derive the displayed
Prediction Accuracy.
"""
    )

st.divider()
# ==========================================================
# Current Project Limitations
# ==========================================================

st.header("⚠️ Current Project Limitations")

st.write(
"""
Although StockVision Forecast V2 provides highly accurate
next-day price predictions, the current version has several
intentional limitations.
"""
)

left, right = st.columns(2)

with left:

    st.warning(
"""
### Current Scope

• Predicts only the next trading day

• Uses historical market data

• Supports regression-based forecasting

• Single ML model deployment
"""
    )

with right:

    st.warning(
"""
### Not Included Yet

• News sentiment analysis

• Macroeconomic indicators

• Portfolio optimization

• Multi-day forecasting
"""
    )

st.divider()
# ==========================================================
# Future Roadmap
# ==========================================================

st.header("🚀 Future Roadmap")

road1, road2 = st.columns(2)

with road1:

    st.success(
"""
### Version 3 Ideas

• LSTM Models

• Transformer Models

• News Sentiment Analysis

• Multi-day Forecasting

• Interactive Charts
"""
    )

with road2:

    st.success(
"""
### Production Features

• Cloud Deployment

• Scheduled Daily Predictions

• Email Notifications

• REST API

• Portfolio Analytics
"""
    )

st.divider()

# ==========================================================
# Technology Stack
# ==========================================================

st.header("🛠 Technology Stack")

tech1, tech2, tech3 = st.columns(3)

with tech1:

    st.info(
"""
### Programming

• Python

• Pandas

• NumPy

• Scikit-Learn
"""
    )

with tech2:

    st.info(
"""
### Frontend

• Streamlit

• CSS

• Interactive Dashboard
"""
    )

with tech3:

    st.info(
"""
### Data & Tools

• Yahoo Finance

• PostgreSQL

• Psycopg

• Joblib

• VS Code
"""
    )

st.divider()
# ==========================================================
# Developer Information
# ==========================================================

st.header("👨‍💻 Developer Information")

st.markdown(
"""
| Item | Details |
|------|---------|
| **Project Name** | StockVision Forecast V2 |
| **Project Type** | Machine Learning Stock Forecasting |
| **Prediction Target** | Next Trading Day Closing Price |
| **Machine Learning Model** | Linear Regression |
| **Frontend** | Streamlit |
| **Backend** | Python + Scikit-Learn |
| **Data Source** | Yahoo Finance |
| **Supported Companies** | 472 |
"""
)

st.divider()

# ==========================================================
# Footer
# ==========================================================

footer1, footer2, footer3 = st.columns(3)

with footer1:

    st.caption(
"""
**Module**

About
"""
    )

with footer2:

    st.caption(
"""
**Version**

2.1
"""
    )

with footer3:

    st.caption(
"""
**Status**

Production Ready
"""
    )

st.divider()

st.caption(
"""
© 2026 StockVision Forecast V2

StockVision Forecast V2 is a production-style Machine Learning
application developed to demonstrate an end-to-end stock price
forecasting workflow, including live data acquisition, feature
engineering, prediction generation, PostgreSQL-backed prediction
storage, and automatic prediction verification.
"""
)